{% set name = "redis-server" %}
{% set version = "7.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/redis/redis/archive/refs/tags/{{ version }}.tar.gz
  sha256: a24a1d173c3736fe5945299d8c2a1c3047b5db817e84182b4b9009792c1108d3

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - redis-cli --version
    - redis-server --version

about:
  home: https://redis.io/
  license: SSPL-1.0 OR LicenseRef-RSALv2
  license_file: COPYING
  summary: Advanced key-value cache and store
  description: |
    Redis is an in-memory database that persists on disk. The data model
    is key-value, but many different kind of values are supported: Strings,
    Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps.
  doc_url: https://redis.io/
  dev_url: https://github.com/redis/redis

extra:
  recipe-maintainers:
    - xhochy
    - SimonBoothroyd
    - wuillaum
