{% set name = "redis-server" %}
{% set version = "7.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/redis/redis/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2853b0848c5e78429d28adb9ae2e2b3f03781a3e547a485df2926fa2e4093e95
  patches:
    - patches/force_c11.patch  # [osx]

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - redis-cli --version
    - redis-server --version

about:
  home: https://redis.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Advanced key-value cache and store
  description: |
    Redis is an in-memory database that persists on disk. The data model
    is key-value, but many different kind of values are supported: Strings,
    Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps.
  doc_url: https://redis.io/
  dev_url: https://github.com/redis/redis

extra:
  recipe-maintainers:
    - SimonBoothroyd
