schema_version: 1

context:
  name: redis-server
  version: "8.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/redis/redis/archive/refs/tags/${{ version }}.tar.gz
  sha256: b928cf47427b94bb0c6866c32df834bc8e5efc815b9ad2e2d24bf33f2c533e2a

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - pkg-config
    - make
  host:
    - jemalloc
    - openssl

tests:
  - script:
      - redis-cli --version
      - redis-server --version

about:
  license: SSPL-1.0 OR LicenseRef-RSALv2
  license_file: LICENSE.txt
  summary: Advanced key-value cache and store
  description: |
    Redis is an in-memory database that persists on disk. The data model
    is key-value, but many different kind of values are supported: Strings,
    Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps.
  homepage: https://redis.io/
  repository: https://github.com/redis/redis
  documentation: https://redis.io/

extra:
  recipe-maintainers:
    - xhochy
    - SimonBoothroyd
