schema_version: 1

context:
  name: redis-server
  version: 8.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/redis/redis/archive/refs/tags/${{ version }}.tar.gz
  sha256: caf3c0069f06fc84c5153bd2a348b204c578de80490c73857bee01d9b5d7401f
  patches:
    - if: osx
      then: "0001-macos-fix.patch"

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib("c") }}
    - make
    - cmake
    - pkg-config
    - clang-tools
  host:
    - openssl
    - libboost-devel
    - libxcrypt
  run:
    - openssl

tests:
  - script:
      - redis-cli --version
      - redis-server --version

about:
  license: SSPL-1.0 OR LicenseRef-RSALv2
  license_file: LICENSE.txt
  summary: Advanced key-value cache and store
  description: |
    Redis is an in-memory database that persists on disk. The data model
    is key-value, but many different kind of values are supported: Strings,
    Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps.
  homepage: https://redis.io/
  repository: https://github.com/redis/redis
  documentation: https://redis.io/

extra:
  recipe-maintainers:
    - xhochy
    - SimonBoothroyd
    - "0xbe7a"
